Rename NuGet.Frameworks to Chocolatey.NuGet.Frameworks
chocolatey/NuGet.Client pull request #10
Opened 2022-11-28 17:10 UTC by gep13

TODO

2022-11-28 17:11 UTC, gep13 commented
@AdmiringWorm I need to put some words into the description here, but I wanted to get this off of my machine.  Let me know if you have any questions about the changes here.

2022-11-30 12:32 UTC, AdmiringWorm requested changes
Partial review, need to finish it up at some point later.

However, I noticed a lot of the files you have changed you have added a `Chocolatey Specific Modification` in the top of the file, instead of going with the existing convention we have for other projects (and previous modifications) that wraps these in a `Start`/`End` block. Any reason for this?

Just having the comment at the top won't help too much if we encounter merge conflicts when we update the library to what is latest upstream...

2022-11-30 12:32 UTC, AdmiringWorm commented on build/config.props
> +    <MS_PFX_PATH>$(MSBuildThisFileDirectory)..\keys\35MSSharedLib1024.snk</MS_PFX_PATH>
Just to confirm, these are the original values from upstream?

2022-11-30 12:32 UTC, AdmiringWorm commented on build/sign.targets
> +    <PublicSign Condition="'$(IsXplat)' == 'true'">true</PublicSign>
Just to confirm, are these the original values from upstream?

2022-11-30 12:32 UTC, AdmiringWorm commented on setup/Microsoft.VisualStudio.NuGet.BuildTools.swr
>          file source=$(ReferenceOutputPath)cs\NuGet.Build.Tasks.resources.dll
Since you are renaming pretty much all libraries, shouldn't this also be renamed?

2022-11-30 12:32 UTC, AdmiringWorm commented on setup/Microsoft.VisualStudio.NuGet.BuildTools.swr
>          file source=$(ReferenceOutputPath)de\NuGet.Build.Tasks.resources.dll
Since you are renaming pretty much all libraries, shouldn't this also be renamed?

2022-11-30 12:32 UTC, AdmiringWorm commented on setup/Microsoft.VisualStudio.NuGet.BuildTools.swr
>          file source=$(ReferenceOutputPath)es\NuGet.Build.Tasks.resources.dll
Since you are renaming pretty much all libraries, shouldn't this also be renamed?

2022-11-30 12:32 UTC, AdmiringWorm commented on setup/Microsoft.VisualStudio.NuGet.BuildTools.swr
>          file source=$(ReferenceOutputPath)fr\NuGet.Build.Tasks.resources.dll
Since you are renaming pretty much all libraries, shouldn't this also be renamed?

2022-11-30 12:32 UTC, AdmiringWorm commented on setup/Microsoft.VisualStudio.NuGet.BuildTools.swr
>          file source=$(ReferenceOutputPath)it\NuGet.Build.Tasks.resources.dll
Since you are renaming pretty much all libraries, shouldn't this also be renamed?

2022-11-30 12:32 UTC, AdmiringWorm commented on setup/Microsoft.VisualStudio.NuGet.BuildTools.swr
>          file source=$(ReferenceOutputPath)ja\NuGet.Build.Tasks.resources.dll
Since you are renaming pretty much all libraries, shouldn't this also be renamed?

2022-11-30 12:32 UTC, AdmiringWorm commented on setup/Microsoft.VisualStudio.NuGet.BuildTools.swr
>          file source=$(ReferenceOutputPath)ko\NuGet.Build.Tasks.resources.dll
Since you are renaming pretty much all libraries, shouldn't this also be renamed?

2022-11-30 12:32 UTC, AdmiringWorm commented on setup/Microsoft.VisualStudio.NuGet.BuildTools.swr
>          file source=$(ReferenceOutputPath)pl\NuGet.Build.Tasks.resources.dll
Since you are renaming pretty much all libraries, shouldn't this also be renamed?

2022-11-30 12:32 UTC, AdmiringWorm commented on setup/Microsoft.VisualStudio.NuGet.BuildTools.swr
>          file source=$(ReferenceOutputPath)pt-BR\NuGet.Build.Tasks.resources.dll
Since you are renaming pretty much all libraries, shouldn't this also be renamed?

2022-11-30 12:32 UTC, AdmiringWorm commented on setup/Microsoft.VisualStudio.NuGet.BuildTools.swr
>          file source=$(ReferenceOutputPath)ru\NuGet.Build.Tasks.resources.dll
Since you are renaming pretty much all libraries, shouldn't this also be renamed?

2022-11-30 12:32 UTC, AdmiringWorm commented on setup/Microsoft.VisualStudio.NuGet.BuildTools.swr
>          file source=$(ReferenceOutputPath)tr\NuGet.Build.Tasks.resources.dll
Since you are renaming pretty much all libraries, shouldn't this also be renamed?

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.CommandLine/Common/InstallCommandProject.cs
> +//////////////////////////////////////////////////////////
Same as before, since we don't own the file. Shouldn't this be wrapped around the change itself?

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.CommandLine/Common/MSBuildProjectSystem.cs
> +//////////////////////////////////////////////////////////
Same as before, since we don't own the file. Shouldn't this be wrapped around the change itself?

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.CommandLine/Common/ResourceHelper.cs
> +// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
Since we haven't made any changes to this file, should we update the copyright here?

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.CommandLine/MsBuildUtility.cs
> +//////////////////////////////////////////////////////////
Same as before, since we don't own the file. Shouldn't this be wrapped around the change itself?

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.CommandLine/NuGet.CommandLine.csproj
> -    <PackageId>NuGet.CommandLine</PackageId>
This doesn't look like we are the ones that introduced the package id here. So this should probably not be removed.

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.CommandLine/Properties/AssemblyInfo.cs
> +[assembly: InternalsVisibleTo("NuGet.CommandLine.Test, PublicKey=002400000480000094000000060200000024000052534131000400000100010007d1fa57c4aed9f0a32e84aa0faefd0de9e8fd6aec8f87fb03766c834c99921eb23be7
Why are you removing the start and end modification comments?

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.CommandLine/ilmerge.props
> +    <MergeInclude Include="$(OutputPath)Chocolatey.NuGet.Versioning.dll"/>
```suggestion
    <!-- //////////////////////////////////////////////////////////
         // Start - Chocolatey Specific Modifications
         ////////////////////////////////////////////////////////// -->
    <MergeInclude Include="$(OutputPath)Chocolatey.NuGet.Build.Tasks.dll"/>
    <MergeInclude Include="$(OutputPath)Chocolatey.NuGet.Commands.dll"/>
    <MergeInclude Include="$(OutputPath)Chocolatey.NuGet.Common.dll"/>
    <MergeInclude Include="$(OutputPath)Chocolatey.NuGet.Configuration.dll"/>
    <MergeInclude Include="$(OutputPath)Chocolatey.NuGet.Credentials.dll"/>
    <MergeInclude Include="$(OutputPath)Chocolatey.NuGet.DependencyResolver.Core.dll"/>
    <MergeInclude Include="$(OutputPath)Chocolatey.NuGet.Frameworks.dll"/>
    <MergeInclude Include="$(OutputPath)Chocolatey.NuGet.LibraryModel.dll"/>
    <MergeInclude Include="$(OutputPath)Chocolatey.NuGet.PackageManagement.dll"/>
    <MergeInclude Include="$(OutputPath)Chocolatey.NuGet.Packaging.dll"/>
    <MergeInclude Include="$(OutputPath)Chocolatey.NuGet.ProjectModel.dll"/>
    <MergeInclude Include="$(OutputPath)Chocolatey.NuGet.Protocol.dll"/>
    <MergeInclude Include="$(OutputPath)Chocolatey.NuGet.Resolver.dll"/>
    <MergeInclude Include="$(OutputPath)Chocolatey.NuGet.Versioning.dll"/>
    <!-- //////////////////////////////////////////////////////////
         // End - Chocolatey Specific Modifications
         ////////////////////////////////////////////////////////// -->
```

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.Console/Properties/AssemblyInfo.cs
> +[assembly: InternalsVisibleTo("NuGet.PowerShellHost.Test, PublicKey=0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889
Why are you removing the modification comments?

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.MSSigning.Extensions/ilmerge.props
> +    <MergeInclude Include="$(OutputPath)Chocolatey.NuGet.Versioning.dll"/>
```suggestion
    <!-- //////////////////////////////////////////////////////////
         // Start - Chocolatey Specific Modifications
         ////////////////////////////////////////////////////////// -->
    <MergeInclude Include="$(OutputPath)Chocolatey.NuGet.Build.Tasks.dll"/>
    <MergeInclude Include="$(OutputPath)Chocolatey.NuGet.Commands.dll"/>
    <MergeInclude Include="$(OutputPath)Chocolatey.NuGet.Common.dll"/>
    <MergeInclude Include="$(OutputPath)Chocolatey.NuGet.Configuration.dll"/>
    <MergeInclude Include="$(OutputPath)Chocolatey.NuGet.Credentials.dll"/>
    <MergeInclude Include="$(OutputPath)Chocolatey.NuGet.DependencyResolver.Core.dll"/>
    <MergeInclude Include="$(OutputPath)Chocolatey.NuGet.Frameworks.dll"/>
    <MergeInclude Include="$(OutputPath)Chocolatey.NuGet.LibraryModel.dll"/>
    <MergeInclude Include="$(OutputPath)Chocolatey.NuGet.PackageManagement.dll"/>
    <MergeInclude Include="$(OutputPath)Chocolatey.NuGet.Packaging.dll"/>
    <MergeInclude Include="$(OutputPath)Chocolatey.NuGet.ProjectModel.dll"/>
    <MergeInclude Include="$(OutputPath)Chocolatey.NuGet.Protocol.dll"/>
    <MergeInclude Include="$(OutputPath)Chocolatey.NuGet.Resolver.dll"/>
    <MergeInclude Include="$(OutputPath)Chocolatey.NuGet.Versioning.dll"/>
    <!-- //////////////////////////////////////////////////////////
         // End - Chocolaty Specific Modifications
         ////////////////////////////////////////////////////////// -->
```

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.PackageManagement.PowerShellCmdlets/Utility/PowerShellCmdletsUtility.cs
> +//////////////////////////////////////////////////////////
Since we don't own this file, the comment should probably wrap around the changes.

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Converters/NuGetFrameworkToStringConverter.cs
> +//////////////////////////////////////////////////////////
Since we don't own this file, the comment should probably wrap around the changes.

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Converters/NuGetFrameworkToVisibilityConverter.cs
> +//////////////////////////////////////////////////////////
Since we don't own this file, the comment should probably wrap around the changes.

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.PackageManagement.UI/Models/PackageDependencySetMetadata.cs
> +//////////////////////////////////////////////////////////
Since we don't own this file, the comment should probably wrap around the changes.

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.PackageManagement.UI/PackageLoadContext.cs
> +//////////////////////////////////////////////////////////
Since we don't own this file, the comment should probably wrap around the changes.

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.PackageManagement.UI/UserInterfaceService/NuGetUI.cs
> +//////////////////////////////////////////////////////////
Since we don't own this file, the comment should probably wrap around the changes.

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Common/IProjectContextInfoExtensions.cs
> +//////////////////////////////////////////////////////////
Since we don't own this file, the comment should probably wrap around the changes.

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/GlobalSuppressions.cs
> +//////////////////////////////////////////////////////////
Since we don't own this file, the comment should probably wrap around the changes.

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/ProjectServices/CpsProjectSystemReferenceReader.cs
> +//////////////////////////////////////////////////////////
Since we don't own this file, the comment should probably wrap around the changes.

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/ProjectServices/NativeProjectSystemReferencesReader.cs
> +//////////////////////////////////////////////////////////
Since we don't own this file, the comment should probably wrap around the changes.

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/ProjectServices/VsCoreProjectSystemReferenceReader.cs
> +//////////////////////////////////////////////////////////
Since we don't own this file, the comment should probably wrap around the changes.

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/ProjectServices/VsManagedLanguagesProjectSystemServices.cs
> +//////////////////////////////////////////////////////////
Since we don't own this file, the comment should probably wrap around the changes.

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/ProjectSystems/VsMSBuildProjectSystem.cs
> +//////////////////////////////////////////////////////////
Since we don't own this file, the comment should probably wrap around the changes.

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/CpsPackageReferenceProject.cs
> +//////////////////////////////////////////////////////////
Since we don't own this file, the comment should probably wrap around the changes.

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/FrameworkInstalledPackages.cs
> +//////////////////////////////////////////////////////////
Since we don't own this file, the comment should probably wrap around the changes.

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/LegacyPackageReferenceProject.cs
> +//////////////////////////////////////////////////////////
Since we don't own this file, the comment should probably wrap around the changes.

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/LegacyPackageReferenceProjectProvider.cs
> +//////////////////////////////////////////////////////////
Since we don't own this file, the comment should probably wrap around the changes.

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/PackageReferenceProject.cs
> +//////////////////////////////////////////////////////////
Since we don't own this file, the comment should probably wrap around the changes.

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.VisualStudio.Client/.vsixinclude
> +Chocolatey.NuGet.Credentials.dll
```suggestion
# //////////////////////////////////////////
# Start - Chocolatey Specific Modifications
# //////////////////////////////////////////
Chocolatey.NuGet.Credentials.dll
# //////////////////////////////////////////
# End - Chocolatey Specific Modifications
# //////////////////////////////////////////
```

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.VisualStudio.Client/.vsixinclude
> +Chocolatey.NuGet.VisualStudio.dll
```suggestion
# //////////////////////////////////////////
# Start - Chocolatey Specific Modifications
# //////////////////////////////////////////
Chocolatey.NuGet.VisualStudio.dll
# //////////////////////////////////////////
# End - Chocolatey Specific Modifications
# //////////////////////////////////////////
```

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.VisualStudio.Client/.vsixinclude
> +Chocolatey.NuGet.VisualStudio.Contracts.dll
```suggestion
# //////////////////////////////////////////
# Start - Chocolatey Specific Modifications
# //////////////////////////////////////////
Chocolatey.NuGet.VisualStudio.Contracts.dll
# //////////////////////////////////////////
# End - Chocolatey Specific Modifications
# //////////////////////////////////////////
```

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.VisualStudio.Client/.vsixinclude
> +Chocolatey.NuGet.PackageManagement.dll
```suggestion
# //////////////////////////////////////////
# Start - Chocolatey Specific Modifications
# //////////////////////////////////////////
Chocolatey.Microsoft.Build.NuGetSdkResolver.dll
Chocolatey.NuGet.Build.Tasks.dll
Chocolatey.NuGet.Commands.dll
Chocolatey.NuGet.Common.dll
Chocolatey.NuGet.Configuration.dll
Chocolatey.NuGet.DependencyResolver.Core.dll
Chocolatey.NuGet.Frameworks.dll
Chocolatey.NuGet.Indexing.dll
Chocolatey.NuGet.LibraryModel.dll
Chocolatey.NuGet.PackageManagement.dll
# //////////////////////////////////////////
# End - Chocolatey Specific Modifications
# //////////////////////////////////////////
```

2022-11-30 12:32 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.VisualStudio.Client/.vsixinclude
> +Chocolatey.NuGet.Versioning.dll
```suggestion
# //////////////////////////////////////////
# Start - Chocolatey Specific Modifications
# //////////////////////////////////////////
Chocolatey.NuGet.Packaging.dll
Chocolatey.NuGet.ProjectModel.dll
Chocolatey.NuGet.Protocol.dll
Chocolatey.NuGet.Resolver.dll
Chocolatey.NuGet.Versioning.dll
# //////////////////////////////////////////
# End - Chocolatey Specific Modifications
# //////////////////////////////////////////
```

2022-12-02 09:46 UTC, gep13 commented on setup/Microsoft.VisualStudio.NuGet.BuildTools.swr
>          file source=$(ReferenceOutputPath)cs\NuGet.Build.Tasks.resources.dll
:+1:

2022-12-02 09:46 UTC, gep13 commented on setup/Microsoft.VisualStudio.NuGet.BuildTools.swr
>          file source=$(ReferenceOutputPath)de\NuGet.Build.Tasks.resources.dll
:+1:

2022-12-02 09:46 UTC, gep13 commented on setup/Microsoft.VisualStudio.NuGet.BuildTools.swr
>          file source=$(ReferenceOutputPath)es\NuGet.Build.Tasks.resources.dll
:+1:

2022-12-02 09:46 UTC, gep13 commented on setup/Microsoft.VisualStudio.NuGet.BuildTools.swr
>          file source=$(ReferenceOutputPath)fr\NuGet.Build.Tasks.resources.dll
:+1:

2022-12-02 09:46 UTC, gep13 commented on setup/Microsoft.VisualStudio.NuGet.BuildTools.swr
>          file source=$(ReferenceOutputPath)it\NuGet.Build.Tasks.resources.dll
:+1:

2022-12-02 09:46 UTC, gep13 commented on setup/Microsoft.VisualStudio.NuGet.BuildTools.swr
>          file source=$(ReferenceOutputPath)ja\NuGet.Build.Tasks.resources.dll
:+1:

2022-12-02 09:46 UTC, gep13 commented on setup/Microsoft.VisualStudio.NuGet.BuildTools.swr
>          file source=$(ReferenceOutputPath)ko\NuGet.Build.Tasks.resources.dll
:+1:

2022-12-02 09:46 UTC, gep13 commented on setup/Microsoft.VisualStudio.NuGet.BuildTools.swr
>          file source=$(ReferenceOutputPath)pl\NuGet.Build.Tasks.resources.dll
:+1:

2022-12-02 09:46 UTC, gep13 commented on setup/Microsoft.VisualStudio.NuGet.BuildTools.swr
>          file source=$(ReferenceOutputPath)pt-BR\NuGet.Build.Tasks.resources.dll
:+1:

2022-12-02 09:46 UTC, gep13 commented on setup/Microsoft.VisualStudio.NuGet.BuildTools.swr
>          file source=$(ReferenceOutputPath)ru\NuGet.Build.Tasks.resources.dll
:+1:

2022-12-02 09:46 UTC, gep13 commented on setup/Microsoft.VisualStudio.NuGet.BuildTools.swr
>          file source=$(ReferenceOutputPath)tr\NuGet.Build.Tasks.resources.dll
:+1:

2022-12-02 09:46 UTC, gep13 commented on setup/Microsoft.VisualStudio.NuGet.BuildTools.swr
>          file source=$(ReferenceOutputPath)zh-Hans\NuGet.Build.Tasks.resources.dll
:+1:

2022-12-02 09:46 UTC, gep13 commented on setup/Microsoft.VisualStudio.NuGet.BuildTools.swr
>          file source=$(ReferenceOutputPath)zh-Hant\NuGet.Build.Tasks.resources.dll
:+1:

2022-12-02 12:03 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Frameworks/Strings.Designer.cs
> +namespace Chocolatey.NuGet.Frameworks
You have removed the needed curly brace

```suggestion
namespace Chocolatey.NuGet.Frameworks {
```

2022-12-02 12:05 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.PackageManagement/GlobalSuppressions.cs
> +[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'GatherCacheResult GatherCache.GetPackage(PackageSource source, PackageIdentity package, NuGetFramework framework)', validate
```suggestion
//////////////////////////////////////////////////////////
// Start - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'GatherCacheResult GatherCache.GetPackage(PackageSource source, PackageIdentity package, NuGetFramework framework)', validate parameter 'package' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.PackageManagement.GatherCache.GetPackage(NuGet.Configuration.PackageSource,NuGet.Packaging.Core.PackageIdentity,Chocolatey.NuGet.Frameworks.NuGetFramework)~NuGet.PackageManagement.GatherCacheResult")]
//////////////////////////////////////////////////////////
// End - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
```

2022-12-02 12:06 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.PackageManagement/GlobalSuppressions.cs
> +[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'Task<ResolvedPackage> NuGetPackageManager.GetLatestVersionAsync(string packageId, NuGetFramework framework, ResolutionContext
```suggestion
//////////////////////////////////////////////////////////
// Start - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'Task<ResolvedPackage> NuGetPackageManager.GetLatestVersionAsync(PackageReference package, NuGetFramework framework, ResolutionContext resolutionContext, IEnumerable<SourceRepository> sources, ILogger log, CancellationToken token)', validate parameter 'sources' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.PackageManagement.NuGetPackageManager.GetLatestVersionAsync(NuGet.Packaging.PackageReference,Chocolatey.NuGet.Frameworks.NuGetFramework,NuGet.PackageManagement.ResolutionContext,System.Collections.Generic.IEnumerable{NuGet.Protocol.Core.Types.SourceRepository},NuGet.Common.ILogger,System.Threading.CancellationToken)~System.Threading.Tasks.Task{NuGet.PackageManagement.ResolvedPackage}")]
[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'Task<ResolvedPackage> NuGetPackageManager.GetLatestVersionAsync(string packageId, NuGetFramework framework, ResolutionContext resolutionContext, IEnumerable<SourceRepository> sources, ILogger log, CancellationToken token)', validate parameter 'sources' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.PackageManagement.NuGetPackageManager.GetLatestVersionAsync(System.String,Chocolatey.NuGet.Frameworks.NuGetFramework,NuGet.PackageManagement.ResolutionContext,System.Collections.Generic.IEnumerable{NuGet.Protocol.Core.Types.SourceRepository},NuGet.Common.ILogger,System.Threading.CancellationToken)~System.Threading.Tasks.Task{NuGet.PackageManagement.ResolvedPackage}")]
//////////////////////////////////////////////////////////
// End - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
```

2022-12-02 12:06 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.PackageManagement/GlobalSuppressions.cs
> +[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'Task<IEnumerable<PackageDependencyInfo>> PackageGraphAnalysisUtilities.GetDependencyInfoForPackageIdentitiesAsync(IEnumerable
```suggestion
//////////////////////////////////////////////////////////
// Start - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'Task<IEnumerable<PackageDependencyInfo>> PackageGraphAnalysisUtilities.GetDependencyInfoForPackageIdentitiesAsync(IEnumerable<PackageIdentity> packageIdentities, NuGetFramework nuGetFramework, DependencyInfoResource dependencyInfoResource, SourceCacheContext sourceCacheContext, bool includeUnresolved, ILogger logger, CancellationToken cancellationToken)', validate parameter 'packageIdentities' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.PackageManagement.PackageGraphAnalysisUtilities.GetDependencyInfoForPackageIdentitiesAsync(System.Collections.Generic.IEnumerable{NuGet.Packaging.Core.PackageIdentity},Chocolatey.NuGet.Frameworks.NuGetFramework,NuGet.Protocol.Core.Types.DependencyInfoResource,NuGet.Protocol.Core.Types.SourceCacheContext,System.Boolean,NuGet.Common.ILogger,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{NuGet.Packaging.Core.PackageDependencyInfo}}")]
//////////////////////////////////////////////////////////
// End - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
```

2022-12-02 12:06 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.PackageManagement/GlobalSuppressions.cs
> +[assembly: SuppressMessage("Build", "CA1305:The behavior of 'string.Format(string, object)' could vary based on the current user's locale settings. Replace this call in 'PackagesConfigLockFileUtility
```suggestion
//////////////////////////////////////////////////////////
// Start - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
[assembly: SuppressMessage("Build", "CA1305:The behavior of 'string.Format(string, object)' could vary based on the current user's locale settings. Replace this call in 'PackagesConfigLockFileUtility.FromPackagesConfigFile(string, NuGetFramework, string, CancellationToken)' with a call to 'string.Format(IFormatProvider, string, params object[])'.", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.PackageManagement.Utility.PackagesConfigLockFileUtility.FromPackagesConfigFile(System.String,Chocolatey.NuGet.Frameworks.NuGetFramework,System.String,System.Threading.CancellationToken)~NuGet.ProjectModel.PackagesLockFile")]
//////////////////////////////////////////////////////////
// End - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
```

2022-12-02 12:07 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.PackageManagement/GlobalSuppressions.cs
> +[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'void JsonConfigUtility.AddFramework(JObject json, NuGetFramework framework)', validate parameter 'framework' is non-null befo
```suggestion
//////////////////////////////////////////////////////////
// Start - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'void JsonConfigUtility.AddFramework(JObject json, NuGetFramework framework)', validate parameter 'framework' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectManagement.JsonConfigUtility.AddFramework(Newtonsoft.Json.Linq.JObject,Chocolatey.NuGet.Frameworks.NuGetFramework)")]
//////////////////////////////////////////////////////////
// End - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
```

2022-12-02 12:07 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.PackageManagement/GlobalSuppressions.cs
> +[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'IEnumerable<NuGetFramework> JsonConfigUtility.GetFrameworks(JObject json)', validate parameter 'json' is non-null before usin
```suggestion
//////////////////////////////////////////////////////////
// End - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'IEnumerable<NuGetFramework> JsonConfigUtility.GetFrameworks(JObject json)', validate parameter 'json' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectManagement.JsonConfigUtility.GetFrameworks(Newtonsoft.Json.Linq.JObject)~System.Collections.Generic.IEnumerable{Chocolatey.NuGet.Frameworks.NuGetFramework}")]
//////////////////////////////////////////////////////////
// End - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
```

2022-12-02 12:07 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.PackageManagement/GlobalSuppressions.cs
> +[assembly: SuppressMessage("Build", "CA1822:Member IsUAPFramework does not access instance data and can be marked as static (Shared in VisualBasic)", Justification = "<Pending>", Scope = "member", Ta
```suggestion
//////////////////////////////////////////////////////////
// Start - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'bool ProjectJsonNuGetProject.IsUAPFramework(NuGetFramework framework)', validate parameter 'framework' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectManagement.Projects.ProjectJsonNuGetProject.IsUAPFramework(Chocolatey.NuGet.Frameworks.NuGetFramework)~System.Boolean")]
[assembly: SuppressMessage("Build", "CA1822:Member IsUAPFramework does not access instance data and can be marked as static (Shared in VisualBasic)", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectManagement.Projects.ProjectJsonNuGetProject.IsUAPFramework(Chocolatey.NuGet.Frameworks.NuGetFramework)~System.Boolean")]
//////////////////////////////////////////////////////////
// End - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
```

2022-12-02 12:10 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Packaging/ChocolateyNuspecReader.cs
> +// Copyright (c) Chocolatey Software, Inc.
```suggestion
// Copyright (c) 2022-Present Chocolatey Software, Inc.
```

2022-12-02 12:11 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Packaging/GlobalSuppressions.cs
> +[assembly: SuppressMessage("Build", "CA1303:Method 'SelectionCriteria ManagedCodeCriteria.ForFrameworkAndRuntime(NuGetFramework framework, string runtimeIdentifier)' passes a literal string as parame
```suggestion
//////////////////////////////////////////////////////////
// Start - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
[assembly: SuppressMessage("Build", "CA1303:Method 'SelectionCriteria ManagedCodeCriteria.ForFrameworkAndRuntime(NuGetFramework framework, string runtimeIdentifier)' passes a literal string as parameter 'message' of a call to 'NotSupportedException.NotSupportedException(string message)'. Retrieve the following string(s) from a resource table instead: \"FallbackFramework is not supported.\".", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Client.ManagedCodeConventions.ManagedCodeCriteria.ForFrameworkAndRuntime(Chocolatey.NuGet.Frameworks.NuGetFramework,System.String)~NuGet.ContentModel.SelectionCriteria")]
//////////////////////////////////////////////////////////
// End - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
```

2022-12-02 12:11 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Packaging/GlobalSuppressions.cs
> +[assembly: SuppressMessage("Build", "CA1303:Method 'FrameworkAssemblyReference.FrameworkAssemblyReference(string assemblyName, IEnumerable<NuGetFramework> supportedFrameworks)' passes a literal strin
```suggestion
//////////////////////////////////////////////////////////
// Start - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
[assembly: SuppressMessage("Build", "CA1303:Method 'FrameworkAssemblyReference.FrameworkAssemblyReference(string assemblyName, IEnumerable<NuGetFramework> supportedFrameworks)' passes a literal string as parameter 'message' of a call to 'ArgumentException.ArgumentException(string message)'. Retrieve the following string(s) from a resource table instead: \"assemblyName\".", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.FrameworkAssemblyReference.#ctor(System.String,System.Collections.Generic.IEnumerable{Chocolatey.NuGet.Frameworks.NuGetFramework})")]
//////////////////////////////////////////////////////////
// End - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
```

2022-12-02 12:12 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Packaging/GlobalSuppressions.cs
> +[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'string FrameworksExtensions.GetFrameworkString(NuGetFramework self)', validate parameter 'self' is non-null before using it.
```suggestion
//////////////////////////////////////////////////////////
// Start - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'string FrameworksExtensions.GetFrameworkString(NuGetFramework self)', validate parameter 'self' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.FrameworksExtensions.GetFrameworkString(Chocolatey.NuGet.Frameworks.NuGetFramework)~System.String")]
//////////////////////////////////////////////////////////
// End - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
```

2022-12-02 12:12 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Packaging/GlobalSuppressions.cs
> +[assembly: SuppressMessage("Build", "CA1801:Parameter frameworkProvider of method .ctor is never used. Remove the parameter or use it in the method body.", Justification = "<Pending>", Scope = "membe
```suggestion
//////////////////////////////////////////////////////////
// Start - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
[assembly: SuppressMessage("Build", "CA1801:Parameter frameworkProvider of method .ctor is never used. Remove the parameter or use it in the method body.", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.PackageArchiveReader.#ctor(System.IO.Stream,Chocolatey.NuGet.Frameworks.IFrameworkNameProvider,Chocolatey.NuGet.Frameworks.IFrameworkCompatibilityProvider)")]
//////////////////////////////////////////////////////////
// End - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
```

2022-12-02 12:12 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Packaging/GlobalSuppressions.cs
> +[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'NuGetFramework PackageReaderBase.GetFrameworkFromPath(string path, bool allowSubFolders = false)', validate parameter 'path'
```suggestion
//////////////////////////////////////////////////////////
// Start - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'NuGetFramework PackageReaderBase.GetFrameworkFromPath(string path, bool allowSubFolders = false)', validate parameter 'path' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.PackageReaderBase.GetFrameworkFromPath(System.String,System.Boolean)~Chocolatey.NuGet.Frameworks.NuGetFramework")]
//////////////////////////////////////////////////////////
// End - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
```

2022-12-02 12:13 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Packaging/GlobalSuppressions.cs
> +[assembly: SuppressMessage("Build", "CA1303:Method 'PackagesConfigWriter.PackagesConfigWriter(string fullPath, bool createNew, IFrameworkNameProvider frameworkMappings)' passes a literal string as pa
```suggestion
//////////////////////////////////////////////////////////
// Start - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
[assembly: SuppressMessage("Build", "CA1303:Method 'PackagesConfigWriter.PackagesConfigWriter(Stream stream, bool createNew, IFrameworkNameProvider frameworkMappings)' passes a literal string as parameter 'message' of a call to 'ArgumentException.ArgumentException(string message)'. Retrieve the following string(s) from a resource table instead: \"stream\".", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.PackagesConfigWriter.#ctor(System.IO.Stream,System.Boolean,Chocolatey.NuGet.Frameworks.IFrameworkNameProvider)")]
[assembly: SuppressMessage("Build", "CA1303:Method 'PackagesConfigWriter.PackagesConfigWriter(string fullPath, bool createNew, IFrameworkNameProvider frameworkMappings)' passes a literal string as parameter 'message' of a call to 'ArgumentException.ArgumentException(string message)'. Retrieve the following string(s) from a resource table instead: \"fullPath\".", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.PackagesConfigWriter.#ctor(System.String,System.Boolean,Chocolatey.NuGet.Frameworks.IFrameworkNameProvider)")]
//////////////////////////////////////////////////////////
// End - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
```

2022-12-02 12:13 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Packaging/GlobalSuppressions.cs
> +[assembly: SuppressMessage("ApiDesign", "RS0027:Public API with optional parameter(s) should have the most parameters amongst its public overloads.", Justification = "API already shipped", Scope = "m
```suggestion
//////////////////////////////////////////////////////////
// Start - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
[assembly: SuppressMessage("ApiDesign", "RS0027:Public API with optional parameter(s) should have the most parameters amongst its public overloads.", Justification = "API already shipped", Scope = "member", Target = "~M:NuGet.Packaging.PackageArchiveReader.#ctor(System.String,Chocolatey.NuGet.Frameworks.IFrameworkNameProvider,Chocolatey.NuGet.Frameworks.IFrameworkCompatibilityProvider)")]
//////////////////////////////////////////////////////////
// End - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
```

2022-12-02 12:14 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/ChocolateyManifestMetadata.cs
> +// Copyright (c) Chocolatey Software, Inc.
```suggestion
// Copyright (c) 2022-Present Chocolatey Software, Inc.
```

2022-12-02 12:14 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/ChocolateyPackageBuilder.cs
> +// Copyright (c) Chocolatey Software, Inc.
```suggestion
// Copyright (c) 2022-Present Chocolatey Software, Inc.
```

2022-12-02 12:14 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/IChocolateyPackageMetadata.cs
> +// Copyright (c) Chocolatey Software, Inc.
```suggestion
// Copyright (c) 2022-Present Chocolatey Software, Inc.
```

2022-12-02 12:17 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.ProjectModel/GlobalSuppressions.cs
> +[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'TargetFrameworkInformation PackageSpecExtensions.GetTargetFramework(PackageSpec project, NuGetFramework targetFramework)', va
```suggestion
//////////////////////////////////////////////////////////
// Start - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'TargetFrameworkInformation PackageSpecExtensions.GetTargetFramework(PackageSpec project, NuGetFramework targetFramework)', validate parameter 'project' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.PackageSpecExtensions.GetTargetFramework(NuGet.ProjectModel.PackageSpec,Chocolatey.NuGet.Frameworks.NuGetFramework)~NuGet.ProjectModel.TargetFrameworkInformation")]
//////////////////////////////////////////////////////////
// End - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
```

2022-12-02 12:18 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.ProjectModel/GlobalSuppressions.cs
> +[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'void PackageSpecOperations.AddOrUpdateDependency(PackageSpec spec, PackageDependency dependency, IEnumerable<NuGetFramework>
```suggestion
//////////////////////////////////////////////////////////
// Start - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'void PackageSpecOperations.AddOrUpdateDependency(PackageSpec spec, PackageDependency dependency, IEnumerable<NuGetFramework> frameworksToAdd)', validate parameter 'spec' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.PackageSpecOperations.AddOrUpdateDependency(NuGet.ProjectModel.PackageSpec,NuGet.Packaging.Core.PackageDependency,System.Collections.Generic.IEnumerable{Chocolatey.NuGet.Frameworks.NuGetFramework})")]
//////////////////////////////////////////////////////////
// End - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
```

2022-12-02 12:20 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.ProjectModel/GlobalSuppressions.cs
> +[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'void PackageSpecOperations.AddOrUpdateDependency(PackageSpec spec, PackageIdentity identity, IEnumerable<NuGetFramework> fram
```suggestion
//////////////////////////////////////////////////////////
// Start - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'void PackageSpecOperations.AddOrUpdateDependency(PackageSpec spec, PackageIdentity identity, IEnumerable<NuGetFramework> frameworksToAdd)', validate parameter 'identity' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.PackageSpecOperations.AddOrUpdateDependency(NuGet.ProjectModel.PackageSpec,NuGet.Packaging.Core.PackageIdentity,System.Collections.Generic.IEnumerable{Chocolatey.NuGet.Frameworks.NuGetFramework})")]
//////////////////////////////////////////////////////////
// End - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
```

2022-12-02 12:20 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.ProjectModel/GlobalSuppressions.cs
> +[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'Library PackageSpecReferenceDependencyProvider.GetLibrary(LibraryRange libraryRange, NuGetFramework targetFramework)', valida
```suggestion
//////////////////////////////////////////////////////////
// Start - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'Library PackageSpecReferenceDependencyProvider.GetLibrary(LibraryRange libraryRange, NuGetFramework targetFramework)', validate parameter 'libraryRange' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.PackageSpecReferenceDependencyProvider.GetLibrary(NuGet.LibraryModel.LibraryRange,Chocolatey.NuGet.Frameworks.NuGetFramework)~NuGet.LibraryModel.Library")]
//////////////////////////////////////////////////////////
// End - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
```

2022-12-02 12:21 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.ProjectModel/GlobalSuppressions.cs
> +[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'string ToolPathResolver.GetBestToolDirectoryPath(string packageId, VersionRange versionRange, NuGetFramework framework)', val
```suggestion
//////////////////////////////////////////////////////////
// Start - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'string ToolPathResolver.GetBestToolDirectoryPath(string packageId, VersionRange versionRange, NuGetFramework framework)', validate parameter 'versionRange' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.ToolPathResolver.GetBestToolDirectoryPath(System.String,NuGet.Versioning.VersionRange,Chocolatey.NuGet.Frameworks.NuGetFramework)~System.String")]
//////////////////////////////////////////////////////////
// End - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
```

2022-12-02 12:21 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.ProjectModel/GlobalSuppressions.cs
> +[assembly: SuppressMessage("Build", "CA1308:In method 'GetToolDirectoryPath', replace the call to 'ToLowerInvariant' with 'ToUpperInvariant'.", Justification = "<Pending>", Scope = "member", Target =
```suggestion
//////////////////////////////////////////////////////////
// Start - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
[assembly: SuppressMessage("Build", "CA1062:In externally visible method 'string ToolPathResolver.GetToolDirectoryPath(string packageId, NuGetVersion version, NuGetFramework framework)', validate parameter 'framework' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.ToolPathResolver.GetToolDirectoryPath(System.String,NuGet.Versioning.NuGetVersion,Chocolatey.NuGet.Frameworks.NuGetFramework)~System.String")]
[assembly: SuppressMessage("Build", "CA1308:In method 'GetToolDirectoryPath', replace the call to 'ToLowerInvariant' with 'ToUpperInvariant'.", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.ToolPathResolver.GetToolDirectoryPath(System.String,NuGet.Versioning.NuGetVersion,Chocolatey.NuGet.Frameworks.NuGetFramework)~System.String")]
//////////////////////////////////////////////////////////
// End - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
```

2022-12-02 12:24 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Protocol/GlobalSuppressions.cs
> +[assembly: SuppressMessage("Build", "CA1305:'DependencyInfoResourceV2Feed.ResolvePackages(string, NuGetFramework, SourceCacheContext, ILogger, CancellationToken)' passes 'CultureInfo.CurrentUICulture
```suggestion
//////////////////////////////////////////////////////////
// Start - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
[assembly: SuppressMessage("Build", "CA1305:'DependencyInfoResourceV2Feed.ResolvePackage(PackageIdentity, NuGetFramework, SourceCacheContext, ILogger, CancellationToken)' passes 'CultureInfo.CurrentUICulture' as the 'IFormatProvider' parameter to 'string.Format(IFormatProvider, string, object, object)'. This property returns a culture that is inappropriate for formatting methods.", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Protocol.DependencyInfoResourceV2Feed.ResolvePackage(NuGet.Packaging.Core.PackageIdentity,Chocolatey.NuGet.Frameworks.NuGetFramework,NuGet.Protocol.Core.Types.SourceCacheContext,NuGet.Common.ILogger,System.Threading.CancellationToken)~System.Threading.Tasks.Task{NuGet.Protocol.Core.Types.SourcePackageDependencyInfo}")]
[assembly: SuppressMessage("Build", "CA1305:'DependencyInfoResourceV2Feed.ResolvePackages(string, NuGetFramework, SourceCacheContext, ILogger, CancellationToken)' passes 'CultureInfo.CurrentUICulture' as the 'IFormatProvider' parameter to 'string.Format(IFormatProvider, string, object, object)'. This property returns a culture that is inappropriate for formatting methods.", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Protocol.DependencyInfoResourceV2Feed.ResolvePackages(System.String,Chocolatey.NuGet.Frameworks.NuGetFramework,NuGet.Protocol.Core.Types.SourceCacheContext,NuGet.Common.ILogger,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{NuGet.Protocol.Core.Types.SourcePackageDependencyInfo}}")]
//////////////////////////////////////////////////////////
// End - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
```

2022-12-02 12:24 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Protocol/GlobalSuppressions.cs
> +[assembly: SuppressMessage("Build", "CA1305:'DependencyInfoResourceV3.ResolvePackages(string, NuGetFramework, SourceCacheContext, ILogger, CancellationToken)' passes 'CultureInfo.CurrentUICulture' as
```suggestion
//////////////////////////////////////////////////////////
// Start - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
[assembly: SuppressMessage("Build", "CA1305:'DependencyInfoResourceV3.ResolvePackage(PackageIdentity, NuGetFramework, SourceCacheContext, ILogger, CancellationToken)' passes 'CultureInfo.CurrentUICulture' as the 'IFormatProvider' parameter to 'string.Format(IFormatProvider, string, object, object)'. This property returns a culture that is inappropriate for formatting methods.", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Protocol.DependencyInfoResourceV3.ResolvePackage(NuGet.Packaging.Core.PackageIdentity,Chocolatey.NuGet.Frameworks.NuGetFramework,NuGet.Protocol.Core.Types.SourceCacheContext,NuGet.Common.ILogger,System.Threading.CancellationToken)~System.Threading.Tasks.Task{NuGet.Protocol.Core.Types.SourcePackageDependencyInfo}")]
[assembly: SuppressMessage("Build", "CA1305:'DependencyInfoResourceV3.ResolvePackages(string, NuGetFramework, SourceCacheContext, ILogger, CancellationToken)' passes 'CultureInfo.CurrentUICulture' as the 'IFormatProvider' parameter to 'string.Format(IFormatProvider, string, object, object)'. This property returns a culture that is inappropriate for formatting methods.", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Protocol.DependencyInfoResourceV3.ResolvePackages(System.String,Chocolatey.NuGet.Frameworks.NuGetFramework,NuGet.Protocol.Core.Types.SourceCacheContext,NuGet.Common.ILogger,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{NuGet.Protocol.Core.Types.SourcePackageDependencyInfo}}")]
//////////////////////////////////////////////////////////
// End - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
```

2022-12-02 12:24 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Protocol/GlobalSuppressions.cs
> +[assembly: SuppressMessage("Build", "CA1305:'LocalDependencyInfoResource.ResolvePackages(string, NuGetFramework, SourceCacheContext, ILogger, CancellationToken)' passes 'CultureInfo.CurrentUICulture'
```suggestion
//////////////////////////////////////////////////////////
// Start - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
[assembly: SuppressMessage("Build", "CA1305:'LocalDependencyInfoResource.ResolvePackage(PackageIdentity, NuGetFramework, SourceCacheContext, ILogger, CancellationToken)' passes 'CultureInfo.CurrentUICulture' as the 'IFormatProvider' parameter to 'string.Format(IFormatProvider, string, object, object)'. This property returns a culture that is inappropriate for formatting methods.", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Protocol.LocalDependencyInfoResource.ResolvePackage(NuGet.Packaging.Core.PackageIdentity,Chocolatey.NuGet.Frameworks.NuGetFramework,NuGet.Protocol.Core.Types.SourceCacheContext,NuGet.Common.ILogger,System.Threading.CancellationToken)~System.Threading.Tasks.Task{NuGet.Protocol.Core.Types.SourcePackageDependencyInfo}")]
[assembly: SuppressMessage("Build", "CA1303:Method 'Task<SourcePackageDependencyInfo> LocalDependencyInfoResource.ResolvePackage(PackageIdentity package, NuGetFramework projectFramework, SourceCacheContext sourceCacheContext, ILogger log, CancellationToken token)' passes a literal string as parameter 'message' of a call to 'ArgumentNullException.ArgumentNullException(string paramName, string message)'. Retrieve the following string(s) from a resource table instead: \"package\".", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Protocol.LocalDependencyInfoResource.ResolvePackage(NuGet.Packaging.Core.PackageIdentity,Chocolatey.NuGet.Frameworks.NuGetFramework,NuGet.Protocol.Core.Types.SourceCacheContext,NuGet.Common.ILogger,System.Threading.CancellationToken)~System.Threading.Tasks.Task{NuGet.Protocol.Core.Types.SourcePackageDependencyInfo}")]
[assembly: SuppressMessage("Build", "CA1305:'LocalDependencyInfoResource.ResolvePackages(string, NuGetFramework, SourceCacheContext, ILogger, CancellationToken)' passes 'CultureInfo.CurrentUICulture' as the 'IFormatProvider' parameter to 'string.Format(IFormatProvider, string, object, object)'. This property returns a culture that is inappropriate for formatting methods.", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Protocol.LocalDependencyInfoResource.ResolvePackages(System.String,Chocolatey.NuGet.Frameworks.NuGetFramework,NuGet.Protocol.Core.Types.SourceCacheContext,NuGet.Common.ILogger,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{NuGet.Protocol.Core.Types.SourcePackageDependencyInfo}}")]
//////////////////////////////////////////////////////////
// End - Chocolatey Specific Modification
//////////////////////////////////////////////////////////
```

2022-12-02 12:25 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Protocol/HttpSource/IHttpSource.cs
> +// Copyright (c) Chocolatey Software, Inc.
```suggestion
// Copyright (c) 2022-Present Chocolatey Software, Inc.
```

2022-12-02 12:25 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Protocol/LegacyFeed/ChocolateyV2FeedPackageInfo.cs
> +// Copyright (c) Chocolatey Software, Inc.
```suggestion
// Copyright (c) 2022-Present Chocolatey Software, Inc.
```

2022-12-02 12:26 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Protocol/LegacyFeed/ChocolateyV2FeedParser.cs
> +// Copyright (c) Chocolatey Software, Inc.
```suggestion
// Copyright (c) 2022-Present Chocolatey Software, Inc.
```

2022-12-02 15:38 UTC, AdmiringWorm approved these changes
LGTM

2022-12-02 15:39 UTC, AdmiringWorm commented
Although it fails here on GH Actions, it succeeds on our internal build server.
As such, I'll get this merged.

2022-12-02 15:40 UTC, merged

2022-12-02 15:40 UTC, AdmiringWorm commented
@gep13 Awesome work. Thank you for getting all of this updated.