(#9) Alter filter construction for prereleases
chocolatey/NuGet.Client pull request #30
Opened 2023-03-13 11:38 UTC by gep13

## Description Of Changes

When the prerelease option is included in the outgoing query, a decision is made about including either IsLatestVersion is IsAbsoluteLatestVersion in the query.  However, in the case where preelease is true and the feed being queried doesn't support IsAbsoluteLatestVersion, the IsLatestVersion is included in the query.

This is deemed as wrong, since it is the exact opposite of what is being asked for.

This commit addresses this issue specifically by only including IsLatestVersion when explicitly not asking for prerelease.  We believe that this will prevent confusion when folks are using Chocolatey.

## Motivation and Context

To prevent confusion of users.

## Testing

1. Check out this PR, and build the NuGet.Client solution
2. Pull the changes into Chocolatey source code
3. Open fiddler on your machine
4. Ensure that you have a valid license file in place in debug version of Chocolatey
5. Run the following command `search chocolatey-agent --pre --source=chocolatey.licensed --proxy=http://localhost:8888`
6. Verify that in the emitted query, that there is no mention of IsLatestVersion

### Operating Systems Testing

- Windows 10/11

## Change Types Made

* [x] Bug fix (non-breaking change).
* [ ] Feature / Enhancement (non-breaking change).
* [ ] Breaking change (fix or feature that could cause existing functionality to change).
* [ ] Documentation changes.
* [ ] PowerShell code changes.

## Change Checklist

* [ ] Requires a change to the documentation.
* [ ] Documentation has been updated.
* [ ] Tests to cover my changes, have been added. (Tests has not been updated, as I do not know which are affected by localization and which may have been affected by the update, tests will instead be enabled or added to Chocolatey CLI E2E)
* [x] All new and existing tests passed? (More tests has been made English only since the last update, unable to verify whether they succeed or not)
* [ ] PowerShell code changes: PowerShell v2 compatibility checked?

## Related Issues

- #9  
- https://app.clickup.com/t/20540031/PROJ-520

2023-03-13 11:42 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Protocol/LegacyFeed/V2FeedListResource.cs
> +                                OrderBy = SearchOrderBy.Id,
In this specific case, would we want to order it by Version Descending?

Just to try making sure that the highest version is returned first (although that will depend on the server implementation)?

2023-03-13 11:42 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Protocol/LegacyFeed/V2FeedListResource.cs
> +                                OrderBy = SearchOrderBy.Id
Same question as my previous comment

2023-03-13 12:52 UTC, gep13 commented on src/NuGet.Core/NuGet.Protocol/LegacyFeed/V2FeedListResource.cs
> +                                OrderBy = SearchOrderBy.Id,
I think that is a sensible addition. It can't be guaranteed to come from the server that way, but we can at least try.

2023-03-13 12:52 UTC, gep13 commented on src/NuGet.Core/NuGet.Protocol/LegacyFeed/V2FeedListResource.cs
> +                                OrderBy = SearchOrderBy.Id
Same as above.

2023-03-13 16:24 UTC, AdmiringWorm commented
I tested an additional query as well, if I do `choco info chocolatey-agent --pre` or `choco install chocolatey-agent --pre` against the same feed it sets `IsAbsoluteLatestVersion` as well, so those calls probably need to have the same handling.

2023-03-14 07:42 UTC, gep13 commented
@AdmiringWorm that is a great catch! I have fixed up this PR with that additional case.  Can you take a look again, and let me know your thoughts?

2023-03-14 09:48 UTC, AdmiringWorm requested changes

2023-03-14 09:48 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Protocol/LegacyFeed/V2FeedListResource.cs
>              var pageOfResults = await _feedParser.GetPackagesPageAsync(searchTerm, searchFilter, 0, 1, logger, token);
Since it now can pass in null as the SearchFilterType, the results count returned will be higher than just one package, and that version may not even be the highest version available.

Using your testing steps as an example, when calling info on `chocolatey-agent` will return version 0.10.0.
Part of it could possibly be resolved by doing a descending version sort, but that would still not be a guarantee that we get the highest version available.

2023-03-14 09:55 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Protocol/LegacyFeed/V2FeedListResource.cs
>              var pageOfResults = await _feedParser.GetPackagesPageAsync(searchTerm, searchFilter, 0, 1, logger, token);
It is also not a guarantee that only `chocolatey-agent` using the same testing steps will be part of the response (looking at the response gotten back, I also got results of `chocolatey.extension` because it is tagged with `chocolatey-agent`)

2023-03-15 07:33 UTC, gep13 commented
@AdmiringWorm can you take another look at this?  I had to further extend the IV2FeedParser after your changes, as the other method wasn't available when testing.

2023-03-15 12:25 UTC, AdmiringWorm approved these changes
LGTM

2023-03-15 12:25 UTC, merged