Bring in Chocolatey patchset.
chocolatey/NuGet.Client pull request #8
Opened 2022-11-15 11:25 UTC by AdmiringWorm

This brings in the Chocolatey patch set of changes to NuGet.Client.
This no longer includes modifications for side by side installs, or the prototype for adding actions into the package manager class.
It includes the extra two commits from #1 relating to building in Team City

Note that the current develop branch build.ps1 is broken, but is fixed in the upstream `dev` branch by these commits:
https://github.com/NuGet/NuGet.Client/commit/c54393073e90c46d1e8cf38a04b9e0da09eadd5e
https://github.com/NuGet/NuGet.Client/commit/d1620d3bc77030d05e7e76b5adf06c33c4dc8374

Re-creation of the PR made by @TheCakeIsNaOH in PR #7

2022-11-15 13:27 UTC, AdmiringWorm commented on build/sign.targets
> +         // Start - Chocolatey Specific Modification
📝 Need to fix this to be `End` instead of `Start`

2022-11-15 13:27 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.VisualStudio.Internal.Contracts/ChocolateyTransitivePackageSearchMetadata.cs
> +        //////////////////////////////////////////////////////////
📝 should be removed

2022-11-15 13:27 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.VisualStudio.Internal.Contracts/ChocolateyTransitivePackageSearchMetadata.cs
> +        //////////////////////////////////////////////////////////
📝 should be removed

2022-11-15 13:27 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/PackageBuilder.cs
> +             */
Looks like I missed a place, need to fix this.

2022-11-15 13:27 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Packaging/PackageCreation/Xml/PackageMetadataXmlExtensions.cs
> +            // Start - Chocolatey Specific Modification
```suggestion
            // End - Chocolatey Specific Modification
```

2022-11-16 08:37 UTC, gep13 requested changes
Overall, this looks great to me. Just a few suggestions, and minor changes!

2022-11-16 08:37 UTC, gep13 commented on src/NuGet.Clients/NuGet.CommandLine/NuGet.CommandLine.csproj
>      <PackageId>NuGet.CommandLine</PackageId>
Is there a reason that the original `PackageId` has been left here?

2022-11-16 08:37 UTC, gep13 commented on src/NuGet.Clients/NuGet.VisualStudio.Internal.Contracts/ChocolateyTransitivePackageSearchMetadata.cs
> +}
Do we need an End Chocolatey Specific Modification section?

2022-11-16 08:37 UTC, gep13 commented on src/NuGet.Core/NuGet.Common/ClientVersionUtility.cs
> +        private static string _clientVersion = "6.4.1-zlocal.1";
There isn't a Chocolatey Specific modification around this change. Is there a reason?

2022-11-16 08:37 UTC, gep13 commented on src/NuGet.Core/NuGet.Configuration/Proxy/ChocolateyProxyCache.cs
> +}
Do we need a closing section?

2022-11-16 08:37 UTC, gep13 commented on src/NuGet.Core/NuGet.Configuration/Proxy/ProxyCache.cs
> +            // Start - Chocolatey Specific Modification
This should be an eEnd section, right?

2022-11-16 08:37 UTC, gep13 commented on src/NuGet.Core/NuGet.Packaging/ChocolateyNuspecReader.cs
> +
Can we remove the extra line here?

2022-11-16 08:37 UTC, gep13 commented on src/NuGet.Core/NuGet.Packaging/ChocolateyNuspecReader.cs
> +}
Do we need a closing section?

2022-11-16 08:37 UTC, gep13 commented on src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/ChocolateyManifestMetadata.cs
> +}
Do we need a closing section?

2022-11-16 08:37 UTC, gep13 commented on src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/ChocolateyPackageBuilder.cs
> +}
Do we need a closing section?

2022-11-16 08:37 UTC, gep13 commented on src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/IChocolateyPackageMetadata.cs
> +}
Do we need a closing section?

2022-11-16 08:37 UTC, gep13 commented on src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/ManifestMetadata.cs
> +    // Start - Chocolatey Specific Modification
Should this be an end section?

2022-11-16 08:37 UTC, gep13 commented on src/NuGet.Core/NuGet.Packaging/compiler/resources/nuspec.xsd
> +                                 // Start - Chocolatey Specific Modification
This should be an End section, right?

2022-11-16 08:37 UTC, gep13 commented on src/NuGet.Core/NuGet.Protocol/HttpSource/IHttpSource.cs
> +}
Do we need a closing section?

2022-11-16 08:37 UTC, gep13 commented on src/NuGet.Core/NuGet.Protocol/LegacyFeed/ChocolateyV2FeedPackageInfo.cs
> +}
Do we need a closing section?

2022-11-16 08:37 UTC, gep13 commented on src/NuGet.Core/NuGet.Protocol/LegacyFeed/ChocolateyV2FeedParser.cs
> +}
Do we need a closing section?

2022-11-16 08:37 UTC, gep13 commented on src/NuGet.Core/NuGet.Protocol/LegacyFeed/ChocolateyV2FeedParser.cs
> +// Copyright (c) .NET Foundation. All rights reserved.
This is a general comment about any new files that we have added to this repository.... is the Copyright still attributable to the .NET Foundation?

2022-11-16 08:37 UTC, gep13 commented on src/NuGet.Core/NuGet.Protocol/Model/ChocolateyLocalPackageSearchMetadata.cs
> +}
Do we need a closing section?

2022-11-16 08:37 UTC, gep13 commented on src/NuGet.Core/NuGet.Protocol/Model/ChocolateyPackageSearchMetadata.cs
> +}
Do we need a closing section?

2022-11-16 08:37 UTC, gep13 commented on src/NuGet.Core/NuGet.Protocol/Model/ChocolateyPackageSearchMetadataBuilder.cs
> +}
Do we need a closing section?

2022-11-16 08:37 UTC, gep13 commented on src/NuGet.Core/NuGet.Protocol/Model/ChocolateyPackageSearchMetadataV2Feed.cs
> +}
Do we need a closing section?

2022-11-16 08:37 UTC, gep13 commented on src/NuGet.Core/NuGet.Protocol/Model/DownloadCache.cs
> +}
Do we need a closing section?

2022-11-16 08:37 UTC, gep13 commented on src/NuGet.Core/NuGet.Protocol/Model/IChocolateyPackageSearchMetadata.cs
> +}
Do we need a closing section?

2022-11-16 08:37 UTC, gep13 commented on test/NuGet.Clients.Tests/NuGet.PackageManagement.UI.Test/ChocolateyTestPackageSearchMetadata.cs
> +}
Do we need a closing section?

2022-11-16 08:37 UTC, gep13 commented on test/NuGet.Core.Tests/NuGet.Configuration.Test/SettingsTests.cs
> +        [Fact(Skip = "Chocolatey SKIP: Fails when NuGet.config is not created by default")]
Do we need a start/end around this change?

2022-11-16 08:37 UTC, gep13 commented on test/TestUtilities/Test.Utility/Protocol/ChocolateyV3PackageSearchMetadataFixture.cs
> +}
Do we need a closing section?

2022-11-16 16:02 UTC, TheCakeIsNaOH commented on src/NuGet.Clients/NuGet.CommandLine/NuGet.CommandLine.csproj
>      <PackageId>NuGet.CommandLine</PackageId>
Since it is not one of the packages that we would be consuming. This and the Visual Studio specific packages are definitely not going to be used by Chocolatey, unless I'm missing something.

2022-11-21 09:10 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.VisualStudio.Internal.Contracts/ChocolateyTransitivePackageSearchMetadata.cs
> +}
I had already answered this privately, but to have it stored here.

As we are owning this file, there should be no need to have a Start/End section. Rather just a single modification section at the top of the file.

2022-11-21 09:16 UTC, AdmiringWorm commented on src/NuGet.Clients/NuGet.CommandLine/NuGet.CommandLine.csproj
>      <PackageId>NuGet.CommandLine</PackageId>
As we also override the `PackageId` later in the file, I'll get this one removed.

2022-11-21 09:20 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Packaging/ChocolateyNuspecReader.cs
> +}
No, we own the entire file, as such we do not need a closing section.

2022-11-21 09:21 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/ChocolateyManifestMetadata.cs
> +}
As mentioned previously, since we own the file there is no need for a closing section.

2022-11-21 09:22 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/ChocolateyPackageBuilder.cs
> +}
Same as before

2022-11-21 09:26 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Protocol/LegacyFeed/ChocolateyV2FeedPackageInfo.cs
> +}
Same as before

2022-11-21 09:27 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Protocol/LegacyFeed/ChocolateyV2FeedParser.cs
> +// Copyright (c) .NET Foundation. All rights reserved.
As this is most likely never being contributed back to the upstream repository, most likely not.

I am working through the changed and new files based on what has been discussed internally with the new file license header for both added and modified files.

2022-11-21 09:28 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Protocol/LegacyFeed/ChocolateyV2FeedParser.cs
> +}
Not for files we own.

2022-11-21 11:26 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Protocol/Model/ChocolateyLocalPackageSearchMetadata.cs
> +}
No, not in this case.

2022-11-21 11:26 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Protocol/Model/ChocolateyPackageSearchMetadata.cs
> +}
No, not in this case.

2022-11-21 11:27 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Protocol/Model/IChocolateyPackageSearchMetadata.cs
> +}
No, not in this case.

2022-11-21 11:51 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Protocol/HttpSource/IHttpSource.cs
> +}
No, not in this case.

2022-11-21 12:04 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Common/ClientVersionUtility.cs
> +        private static string _clientVersion = "6.4.1-zlocal.1";
I am honestly not completely sure if we need/want this change!

It seems to originally be in the NuGet.Core codebase we had due to a bug: https://github.com/chocolatey/choco/issues/194

I am thinking we may not want this anymore.

2022-11-21 12:06 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Configuration/Proxy/ChocolateyProxyCache.cs
> +}
No, not in this case.

2022-11-21 12:12 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/IChocolateyPackageMetadata.cs
> +}
No, we own the file itself.

2022-11-21 12:16 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Protocol/Model/ChocolateyPackageSearchMetadataBuilder.cs
> +}
No, not in this case. We own the file.

2022-11-21 12:17 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Protocol/Model/ChocolateyPackageSearchMetadataV2Feed.cs
> +}
No, not in this case. We own the file.

2022-11-21 12:17 UTC, AdmiringWorm commented on src/NuGet.Core/NuGet.Protocol/Model/DownloadCache.cs
> +}
Nope.

2022-11-21 12:20 UTC, AdmiringWorm commented on test/TestUtilities/Test.Utility/Protocol/ChocolateyV3PackageSearchMetadataFixture.cs
> +}
Not in this case.

2022-11-21 14:51 UTC, gep13 approved these changes
LGTM!

2022-11-21 14:54 UTC, gep13 commented on src/NuGet.Core/NuGet.Common/ClientVersionUtility.cs
> +        private static string _clientVersion = "6.4.1-zlocal.1";
As discussed, let's leave this in place for now, and we can re-visit once we have taken this for a spin fully once pulled into chocolatey/choco.

2022-11-21 14:55 UTC, merged

2022-11-21 14:55 UTC, gep13 commented
@AdmiringWorm and @TheCakeIsNaOH thanks for getting this to where it is! Now let's take this for a spin, and see what we can figure out within chocolatey/choco!